services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
